Fixed a panic when using the `Router` returned from `*Mux.With(...)` as an http.Handler (#276)
* Fixed a panic when using the `Router` returned from `*Mux.With(...)` as an http.Handler

This panic was a result of the `*Mux` returned from `*Mux.With(...)` not having it's `*Mux.pool.New` function set. The returned `*Mux` is now properly initialized.

Added a test to catch this. Here's what the failure looked like before the fix:

```
> go test -run TestRouterFromMuxWith
2017/10/26 16:48:21 http: panic serving 127.0.0.1:56700: interface conversion: interface {} is nil, not *chi.Context
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc420150000)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:1697 +0xd0
panic(0x12df700, 0xc420088900)
	/usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:491 +0x283
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc420110230, 0x14b04e0, 0xc420174000, 0xc420166000)
	$GOPATH/go/src/github.com/go-chi/chi/mux.go:77 +0x36c
net/http.serverHandler.ServeHTTP(0xc420084ea0, 0x14b04e0, 0xc420174000, 0xc420166000)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420150000, 0x14b0aa0, 0xc420128140)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2720 +0x288
--- FAIL: TestRouterFromMuxWith (0.00s)
	mux_test.go:1527: Get http://127.0.0.1:56699/with_middleware: EOF
FAIL
exit status 1
FAIL	github.com/go-chi/chi	0.021s
```

* Changed initialization of inline *Mux based on feedback from pkieltyka

* Addressing code review comment from pkieltyka